### ISSUE TITLE
How do you remove those invisible labels on Waymo Dataset?

### ISSUE THREAD

**Issue by huangzhengxiang** [zhiqi-li/BEVFormer#89]
Hello! Thanks for your great work!
In your paper, you mentioned that you removed all the invisible labels in waymo dataset. How did you do that? Did you remove them beforehand or everytime you load the ground truth?

**Comment by zhiqi-li** [comment]
Since  the FOV of the camera system in WOD  only covers part of GT, we remove the bounding boxes that cannot be seen in the images. Recently, waymo releases a new version WOD that contains the information that bounding boxes can be seen by camera or not. I recommend you to use the latest WOD and corresponding toolkit,  and it can well support camera-only detection.

**Comment by huangzhengxiang** [comment]
Do you mean that the latest WOD contains all the bounding boxes (nothing is removed), while providing extra information whether the bounding boxes can be seen camera-only at the same time?

**Comment by zhiqi-li** [comment]
yes.
